# HW1 - Linear Regression, Regularization, Preceptron

### Question 1 A - Housing data set Work

In [1]:
# housing data set
import numpy as np

train = np.loadtxt("train.txt")
test = np.loadtxt("test.txt")

train

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 3.9690e+02, 4.9800e+00,
        2.4000e+01],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 3.9690e+02, 9.1400e+00,
        2.1600e+01],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 3.9283e+02, 4.0300e+00,
        3.4700e+01],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 5.6400e+00,
        2.3900e+01],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 3.9345e+02, 6.4800e+00,
        2.2000e+01],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 7.8800e+00,
        1.1900e+01]], shape=(433, 14))

In [2]:
train.shape

(433, 14)

In [3]:
# slicing train into X (features) and y (labels)
X = train[:, :-1]
y = train[:, -1]

In [4]:
X.shape

(433, 13)

In [5]:
y.shape

(433,)

In [6]:
# adding bias to the columns
ones_col = np.ones((X.shape[0], 1))
X_bias = np.hstack([ones_col, X])
X_bias.shape

(433, 14)

In [7]:
X_bias

array([[1.0000e+00, 6.3200e-03, 1.8000e+01, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [1.0000e+00, 2.7310e-02, 0.0000e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [1.0000e+00, 2.7290e-02, 0.0000e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [1.0000e+00, 6.0760e-02, 0.0000e+00, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0000e+00, 1.0959e-01, 0.0000e+00, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [1.0000e+00, 4.7410e-02, 0.0000e+00, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]], shape=(433, 14))

Using normal equation to calculate best weights ($\theta$):

$\theta = (X^T X) ^ {-1} X^T Y$

In [8]:
# taking transpose:
X_t = X_bias.T

# multiplying X_t and X:
X_dot = np.dot(X_t, X_bias)

# taking inverse:
X_inv_1 = np.linalg.inv(X_dot)

# calculation for second term
Xy_dot = np.dot(X_t, y)

best_weights = np.dot(X_inv_1, Xy_dot)
best_weights

array([ 3.95843212e+01, -1.01137046e-01,  4.58935299e-02, -2.73038670e-03,
        3.07201340e+00, -1.72254072e+01,  3.71125235e+00,  7.15862492e-03,
       -1.59900210e+00,  3.73623375e-01, -1.57564197e-02, -1.02417703e+00,
        9.69321451e-03, -5.85969273e-01])

In [9]:
# Evaluation - using MSE
y_pred = np.dot(X_bias, best_weights)

# mse calc:
mse = np.mean((y_pred - y)**2)
mse

np.float64(22.081273187013167)

In [10]:
print("First 5 predictions:", y_pred[:5])
print("First 5 actual:", y[:5])
print("Training MSE:", mse)

First 5 predictions: [30.43342174 25.13122263 30.79404953 28.86491521 28.09585159]
First 5 actual: [24.  21.6 34.7 33.4 36.2]
Training MSE: 22.081273187013167


In [11]:
# checking test MSE scores: (Test set evaluation) (test.txt)
X_test = test[:, :-1]
y_test = test[:,-1]

In [12]:
X_test.shape

(74, 13)

In [13]:
y_test.shape

(74,)

In [14]:
# adding bias to feature column:
test_ones = np.ones((test.shape[0], 1))
testX_bias = np.hstack([test_ones, X_test])

In [15]:
testX_bias.shape

(74, 14)

In [16]:
# prediction of test
test_pred = np.dot(testX_bias, best_weights)
test_pred

array([12.89601587, 15.08480652, 14.14860902, 19.28346642, 20.62441232,
       17.62638194,  8.06630128, 16.79766039, 22.42117946, 22.76515103,
       20.47101225, 21.82726572, 28.30091981, 24.40357762, 25.45408692,
       19.49148616, 20.00375136, 19.46329612, 14.93993312, 12.29624758,
       16.34220081, 14.97974654, 15.83457878,  7.87499641, 22.98187086,
       26.49665188, 26.71380083, 22.42973877, 32.40553743, 34.46425864,
       30.39513616, 30.03396417, 32.703242  , 34.16265404, 24.10820509,
       32.99344005, 23.50402945, 23.71822828, 24.66694602, 24.2994886 ,
       29.2129179 , 36.32323393, 35.81453251, 26.87358108, 19.10110163,
       26.85320042, 13.07264945, 15.44988802, 19.92615667, 23.1354172 ,
       22.69039895, 19.24158123, -0.20477172, 25.48651721, 19.52602437,
       15.78762417, 16.49976921,  0.67980639, 11.72260854, 15.96229042,
       14.09058822, 13.65398333, 11.33040202, 17.5051086 , 18.07776724,
       17.49358502, 13.9234283 , 16.4244096 , 16.55495335, 11.83

In [17]:
test_pred.shape

(74,)

In [18]:
# mse for test:
mse_test = np.mean((test_pred-y_test) ** 2)
mse_test

np.float64(22.63825629657661)

In [19]:
np.min(y_test)

np.float64(10.2)

In [20]:
np.max(y_test)

np.float64(42.8)

In [21]:
np.std(y_test)

np.float64(6.4612466429594)

### Question 1A - Normalized Housing Dataset

In [22]:
house_train = np.loadtxt("train.txt")
house_test = np.loadtxt("test.txt")

house_train.shape

(433, 14)

In [23]:
# separating features and labels
X_train = house_train[:, :-1]
y_train = house_train[:, -1]
X_test = house_test[:, :-1]
y_test = house_test[:, -1]

In [24]:
# applying normalization -
train_mean = np.mean(X_train, axis=0)
train_std = np.std(X_train, axis=0)

X_train_normalized = (X_train - train_mean) / train_std
X_test_normalized = (X_test - train_mean) / train_std

X_train_normalized[:3]

array([[-0.40654388,  0.27198037, -1.27084905, -0.26792196, -0.12875596,
         0.38509581, -0.09515781,  0.14085217, -0.97070059, -0.61306377,
        -1.4510964 ,  0.40955068, -1.04777883],
       [-0.4040825 , -0.48740168, -0.55514244, -0.26792196, -0.72732782,
         0.16863868,  0.3982737 ,  0.56797077, -0.85545152, -0.93587279,
        -0.27507495,  0.40955068, -0.46031379],
       [-0.40408485, -0.48740168, -0.55514244, -0.26792196, -0.72732782,
         1.24249093, -0.2428271 ,  0.56797077, -0.85545152, -0.93587279,
        -0.27507495,  0.36136762, -1.18193551]])

In [25]:
# adding bias to X_train and X_test
ones_col_Xtrain = np.ones((X_train_normalized.shape[0], 1))
ones_col_Xtest = np.ones((X_test_normalized.shape[0], 1))

houseXtrain_bias = np.hstack([ones_col_Xtrain, X_train_normalized])
houseXtest_bias = np.hstack([ones_col_Xtest, X_test_normalized])

In [26]:
# using normal equation:

houseXtrain_transpose = houseXtrain_bias.T

houseXtrain_dot = np.dot(houseXtrain_transpose, houseXtrain_bias)

houseXtrain_inverse = np.linalg.inv(houseXtrain_dot)

houseXtrain_y_dot = np.dot(houseXtrain_transpose, y_train)

house_train_theta = np.dot(houseXtrain_inverse, houseXtrain_y_dot)
house_train_theta

array([ 2.28672055e+01, -8.62471154e-01,  1.08783654e+00, -1.81591739e-02,
        7.67935759e-01, -1.98564814e+00,  2.64039749e+00,  1.98757394e-01,
       -3.28359559e+00,  3.24187760e+00, -2.63575867e+00, -2.17720738e+00,
        8.18781184e-01, -4.14940807e+00])

In [27]:
house_train_pred = np.dot(houseXtrain_bias, house_train_theta)

house_test_pred = np.dot(houseXtest_bias, house_train_theta)

In [28]:
# errors:
house_train_mse = np.mean((house_train_pred - y_train) ** 2)
house_test_mse = np.mean((house_test_pred - y_test) ** 2)

In [58]:
print(f"Housing dataset training mse: {house_train_mse}")

Housing dataset training mse: 22.081273187013167


In [59]:
print(f"Housing dataset testing mse: {house_test_mse}")

Housing dataset testing mse: 22.638256296587716


### Question1A - Spam Dataset Work
with normalization , kfold cross validation and binary predictions

In [31]:
# SPAM dataset loading
data = np.loadtxt("spambase/spambase.data", delimiter=",")

In [32]:
data

array([[0.000e+00, 6.400e-01, 6.400e-01, ..., 6.100e+01, 2.780e+02,
        1.000e+00],
       [2.100e-01, 2.800e-01, 5.000e-01, ..., 1.010e+02, 1.028e+03,
        1.000e+00],
       [6.000e-02, 0.000e+00, 7.100e-01, ..., 4.850e+02, 2.259e+03,
        1.000e+00],
       ...,
       [3.000e-01, 0.000e+00, 3.000e-01, ..., 6.000e+00, 1.180e+02,
        0.000e+00],
       [9.600e-01, 0.000e+00, 0.000e+00, ..., 5.000e+00, 7.800e+01,
        0.000e+00],
       [0.000e+00, 0.000e+00, 6.500e-01, ..., 5.000e+00, 4.000e+01,
        0.000e+00]], shape=(4601, 58))

In [33]:
data.shape

(4601, 58)

In [34]:
X = data[:, :-1]
y = data[:,-1]

ones_col = np.ones((X.shape[0], 1))
spamX_bias = np.hstack([ones_col, X])

spamX_bias.shape

(4601, 58)

In [35]:
spamX_bias[:5]

array([[1.000e+00, 0.000e+00, 6.400e-01, 6.400e-01, 0.000e+00, 3.200e-01,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        6.400e-01, 0.000e+00, 0.000e+00, 0.000e+00, 3.200e-01, 0.000e+00,
        1.290e+00, 1.930e+00, 0.000e+00, 9.600e-01, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 7.780e-01, 0.000e+00,
        0.000e+00, 3.756e+00, 6.100e+01, 2.780e+02],
       [1.000e+00, 2.100e-01, 2.800e-01, 5.000e-01, 0.000e+00, 1.400e-01,
        2.800e-01, 2.100e-01, 7.000e-02, 0.000e+00, 9.400e-01, 2.100e-01,
        7.900e-01, 6.500e-01, 2.100e-01, 1.400e-01, 1.400e-01, 7.000e-02,
        2.800e-01, 3.470e+00, 0.000e+00, 1.590e+00, 0.000e+

In [36]:
# applying normal equation
# taking transpose:
spamX_t = spamX_bias.T

# multiplying X_t and X:
spamX_dot = np.dot(spamX_t, spamX_bias)

# taking inverse:
spamX_inv_1 = np.linalg.inv(spamX_dot)

# calculation for second term
spamXy_dot = np.dot(spamX_t, y)

best_weights = np.dot(spamX_inv_1, spamXy_dot)
best_weights

array([ 2.00278624e-01, -4.98190289e-02, -1.20462357e-02,  3.92785791e-02,
        1.19172872e-02,  8.42077238e-02,  1.18840540e-01,  2.12940544e-01,
        9.39888974e-02,  7.24740307e-02,  1.50673956e-02,  5.68567170e-02,
       -2.78594942e-02,  1.19040396e-02,  4.85997980e-03,  1.85245239e-02,
        7.50613606e-02,  5.17157135e-02,  5.53979180e-02,  1.41333699e-02,
        6.17219769e-02,  5.26937284e-02,  4.47670000e-02,  1.74800431e-01,
        9.08907931e-02, -2.31749678e-02, -2.16289521e-02, -1.22016024e-02,
        3.98741601e-03, -7.44954418e-03, -5.19483779e-02, -2.32939753e-02,
        6.33175996e-03, -4.19834167e-02,  5.11417651e-02, -3.11687177e-02,
        2.64800625e-02, -3.32125168e-02, -5.34386058e-02, -1.97545953e-02,
        4.07608890e-02, -8.36408577e-03, -3.69265209e-02, -6.32389776e-02,
       -3.23800301e-02, -3.52532828e-02, -3.78141111e-02, -1.95177400e-01,
       -5.82229386e-02, -1.40102484e-01, -5.99593550e-02, -5.90515790e-02,
        6.80529871e-02,  

In [37]:
spamy_pred = np.dot(spamX_bias, best_weights)

# threshold :
threshold = 0.431
binary_pred = (spamy_pred > threshold).astype(int)

binary_pred.shape

(4601,)

In [38]:
# accuracy evaluation
accuracy = np.mean(binary_pred == y)
accuracy

np.float64(0.9121930015214084)

In [39]:
spam_min = np.min(spamy_pred)
spam_max = np.max(spamy_pred)

In [40]:
spam_min

np.float64(-0.6515491136232259)

In [41]:
spam_max

np.float64(2.2708321220792214)

### K-Fold cross validation working on Spam dataset

In [42]:
data = np.loadtxt("spambase/spambase.data", delimiter=",")

X = data[:, :-1]
y = data[:,-1]

In [57]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=5, shuffle=True, random_state=42)

train_fold_accuracies = []
test_fold_accuracies = []

for train_index, test_index in kf.split(X):
    X_train_fold = X[train_index]
    X_test_fold = X[test_index]

    y_train_fold = y[train_index]
    y_test_fold = y[test_index]

    # adding normalization:
    train_mean = np.mean(X_train_fold, axis=0)
    train_std = np.std(X_train_fold, axis=0)

    X_train_normalized = (X_train_fold - train_mean) / train_std
    X_test_normalized = (X_test_fold - train_mean) / train_std

    # adding bias:
    ones_col_Xtrain = np.ones((X_train_normalized.shape[0], 1))
    ones_col_Xtest = np.ones((X_test_normalized.shape[0], 1))

    spam_Xtrain_bias = np.hstack([ones_col_Xtrain, X_train_normalized])
    spam_Xtest_bias = np.hstack([ones_col_Xtest, X_test_normalized])

    # model training
    spamXtrain_T = spam_Xtrain_bias.T

    spamXtrain_dot = np.dot(spamXtrain_T, spam_Xtrain_bias)

    spamXtrain_inverse = np.linalg.inv(spamXtrain_dot)

    spamX_y_dot = np.dot(spamXtrain_T, y_train_fold)

    best_weights_X = np.dot(spamXtrain_inverse, spamX_y_dot)

    # predictions:
    train_continuous_predictions = np.dot(spam_Xtrain_bias, best_weights_X)
    test_continuous_predictions = np.dot(spam_Xtest_bias, best_weights_X)

    # threshold for binary classification:
    threshold = 0.43
    test_binary_pred = (test_continuous_predictions > threshold).astype(int)
    train_binary_pred = (train_continuous_predictions > threshold).astype(int)


    # accuracy:
    test_fold_accuracy = np.mean(test_binary_pred == y_test_fold)
    train_fold_accuracy = np.mean(train_binary_pred == y_train_fold)
    test_fold_accuracies.append(test_fold_accuracy)
    train_fold_accuracies.append(train_fold_accuracy)

test_mean_accuracy = np.mean(test_fold_accuracies)
train_mean_accuracy = np.mean(train_fold_accuracies)

print(f"Testing accuracy: {test_mean_accuracy * 100}")
print(f"Training accuracy: {train_mean_accuracy * 100}")

Testing accuracy: 90.80633054808101
Training accuracy: 91.26275941084063


### Question 1B - L2 Regularization

In [44]:
# loading datasets both housing and spam
import numpy as np
house_data_train = np.loadtxt("train.txt")
house_data_test = np.loadtxt("test.txt")

spam_data = np.loadtxt("spambase/spambase.data", delimiter=",")

first going with housing dataset

In [45]:
# splitting data into train and test
house_X = house_data_train[:,:-1]
house_y = house_data_train[:, -1]

In [46]:
# normalization step:
house_train_mean = np.mean(house_X, axis=0)
house_train_std = np.std(house_X, axis=0)

house_X_norm = (house_X-house_train_mean) / house_train_std
house_X_norm[:3]

array([[-0.40654388,  0.27198037, -1.27084905, -0.26792196, -0.12875596,
         0.38509581, -0.09515781,  0.14085217, -0.97070059, -0.61306377,
        -1.4510964 ,  0.40955068, -1.04777883],
       [-0.4040825 , -0.48740168, -0.55514244, -0.26792196, -0.72732782,
         0.16863868,  0.3982737 ,  0.56797077, -0.85545152, -0.93587279,
        -0.27507495,  0.40955068, -0.46031379],
       [-0.40408485, -0.48740168, -0.55514244, -0.26792196, -0.72732782,
         1.24249093, -0.2428271 ,  0.56797077, -0.85545152, -0.93587279,
        -0.27507495,  0.36136762, -1.18193551]])

In [47]:
# adding bias
ones_col = np.ones((house_X_norm.shape[0], 1))
house_X_with_bias = np.hstack([ones_col, house_X_norm])

house_X_with_bias[:3]

array([[ 1.        , -0.40654388,  0.27198037, -1.27084905, -0.26792196,
        -0.12875596,  0.38509581, -0.09515781,  0.14085217, -0.97070059,
        -0.61306377, -1.4510964 ,  0.40955068, -1.04777883],
       [ 1.        , -0.4040825 , -0.48740168, -0.55514244, -0.26792196,
        -0.72732782,  0.16863868,  0.3982737 ,  0.56797077, -0.85545152,
        -0.93587279, -0.27507495,  0.40955068, -0.46031379],
       [ 1.        , -0.40408485, -0.48740168, -0.55514244, -0.26792196,
        -0.72732782,  1.24249093, -0.2428271 ,  0.56797077, -0.85545152,
        -0.93587279, -0.27507495,  0.36136762, -1.18193551]])

L2 Regularization Equation:
$ \theta = (X^TX + \lambda I) X^T Y $

In [48]:
# using normal equation
lambda_1 = 0.43

house_X_transpose = house_X_with_bias.T

dot_X = np.dot(house_X_transpose, house_X_with_bias)  # first term

I_house = np.eye(house_X_with_bias.shape[1])

dot_lambda = lambda_1 * I_house # second term

add_X_lambda = dot_X + dot_lambda

inverse_X_with_lambda = np.linalg.inv(add_X_lambda)

XTy = np.dot(house_X_transpose, house_y)

house_ridge_weights = np.dot(inverse_X_with_lambda, XTy)

house_ridge_weights

array([22.8445193 , -0.85904107,  1.08023413, -0.0268609 ,  0.76961537,
       -1.9746475 ,  2.6469713 ,  0.19472202, -3.27074685,  3.18693213,
       -2.58308442, -2.17140003,  0.81931111, -4.14177781])

In [49]:
train_eval_mse = np.dot(house_X_with_bias, house_ridge_weights)

final_mse_1 = np.mean((train_eval_mse - house_y)**2)

In [50]:
print(f"Training MSE: {final_mse_1}") # training mse

Training MSE: 22.08219671346033


In [51]:
# test mse working:
house_X_test = house_data_test[:,:-1]
house_y_test = house_data_test[:,-1]

house_X_test_norm = (house_X_test - house_train_mean) / house_train_std

ones_col_test = np.ones((house_X_test_norm.shape[0], 1))
house_X_test_bias = np.hstack([ones_col_test, house_X_test_norm])

house_pred_test = np.dot(house_X_test_bias, house_ridge_weights)
mse_house_test = np.mean((house_pred_test - house_y_test) ** 2)
print(f"Testing MSE: {mse_house_test}")

Testing MSE: 22.59834254128926


Spam dataset Working - L2 Regularization :  $ \theta = (X^TX + \lambda I) X^T Y $

In [52]:
from sklearn.model_selection import KFold
import numpy as np

# Define lambda values to test
lambda_values = np.logspace(-2, 1, 7)
results = []

kf = KFold(n_splits=10, shuffle=True, random_state=42)

for lambda_val in lambda_values:
    print(f"Testing λ = {lambda_val}")

    train_fold_accuracies = []
    test_fold_accuracies = []

    for train_index, test_index in kf.split(X):
        X_train_fold = X[train_index]
        X_test_fold = X[test_index]
        y_train_fold = y[train_index]
        y_test_fold = y[test_index]

        # normalization:
        train_mean = np.mean(X_train_fold, axis=0)
        train_std = np.std(X_train_fold, axis=0)
        X_train_normalized = (X_train_fold - train_mean) / train_std
        X_test_normalized = (X_test_fold - train_mean) / train_std

        # adding bias:
        ones_col_Xtrain = np.ones((X_train_normalized.shape[0], 1))
        ones_col_Xtest = np.ones((X_test_normalized.shape[0], 1))
        spam_Xtrain_bias = np.hstack([ones_col_Xtrain, X_train_normalized])
        spam_Xtest_bias = np.hstack([ones_col_Xtest, X_test_normalized])

        # Ridge regression
        spamXtrain_T = spam_Xtrain_bias.T
        spamXtrain_dot = np.dot(spamXtrain_T, spam_Xtrain_bias)
        I_lambda = np.eye(spamXtrain_dot.shape[1])
        add_X_lambda = spamXtrain_dot + lambda_val * I_lambda  # Use current lambda
        spamXtrain_inverse = np.linalg.inv(add_X_lambda)
        spamX_y_dot = np.dot(spamXtrain_T, y_train_fold)
        best_weights_X = np.dot(spamXtrain_inverse, spamX_y_dot)

        # predictions and accuracy
        train_continuous_pred = np.dot(spam_Xtrain_bias, best_weights_X)
        test_continuous_pred = np.dot(spam_Xtest_bias, best_weights_X)

        threshold = 0.43
        test_binary_pred = (test_continuous_pred > threshold).astype(int)
        train_binary_pred = (train_continuous_pred > threshold).astype(int)

        test_fold_accuracy = np.mean(test_binary_pred == y_test_fold)
        train_fold_accuracy = np.mean(train_binary_pred == y_train_fold)

        test_fold_accuracies.append(test_fold_accuracy)
        train_fold_accuracies.append(train_fold_accuracy)

    # Average across folds
    avg_train = np.mean(train_fold_accuracies)
    avg_test = np.mean(test_fold_accuracies)

    results.append((lambda_val, avg_train, avg_test))
    print(f"λ={lambda_val}: Train={avg_train:.3f}, Test={avg_test:.3f}")

Testing λ = 0.01
λ=0.01: Train=0.913, Test=0.910
Testing λ = 0.03162277660168379
λ=0.03162277660168379: Train=0.913, Test=0.910
Testing λ = 0.1
λ=0.1: Train=0.913, Test=0.910
Testing λ = 0.31622776601683794
λ=0.31622776601683794: Train=0.913, Test=0.910
Testing λ = 1.0
λ=1.0: Train=0.913, Test=0.910
Testing λ = 3.1622776601683795
λ=3.1622776601683795: Train=0.913, Test=0.910
Testing λ = 10.0
λ=10.0: Train=0.912, Test=0.910


In [63]:
train_accuracies = [result[1] for result in results]
test_accuracies = [result[2] for result in results]

print(f"\nSUMMARY STATISTICS:")
print(f"Average Training Accuracy: {np.mean(train_accuracies)*100:.1f}%")
print(f"Average Test Accuracy: {np.mean(test_accuracies)*100:.1f}%")
print(f"Best Test Accuracy: {np.max(test_accuracies)*100:.1f}%")
print(f"Average Generalization Gap: {np.mean([r[1]-r[2] for r in results])*100:.1f}%")


SUMMARY STATISTICS:
Average Training Accuracy: 91.3%
Average Test Accuracy: 91.0%
Best Test Accuracy: 91.0%
Average Generalization Gap: 0.3%


In [65]:
train_accuracies = [result[1] for result in results]
test_accuracies = [result[2] for result in results]

print(f"\nSUMMARY STATISTICS:")
print(f"Average Training Accuracy: {np.mean(train_accuracies)*100:.1f}%")
print(f"Average Test Accuracy: {np.mean(test_accuracies)*100:.1f}%")
print(f"Average Generalization Gap: {np.mean([r[1]-r[2] for r in results])*100:.1f}%")

best_test_idx = np.argmax(test_accuracies)
worst_test_idx = np.argmin(test_accuracies)

print(f"\nBEST PERFORMANCE:")
print(f"Lambda: {results[best_test_idx][0]:.3f}")
print(f"Train Accuracy: {results[best_test_idx][1]*100:.1f}%")
print(f"Test Accuracy: {results[best_test_idx][2]*100:.1f}%")

print(f"\nWORST PERFORMANCE:")
print(f"Lambda: {results[worst_test_idx][0]:.3f}")
print(f"Train Accuracy: {results[worst_test_idx][1]*100:.1f}%")
print(f"Test Accuracy: {results[worst_test_idx][2]*100:.1f}%")


SUMMARY STATISTICS:
Average Training Accuracy: 91.3%
Average Test Accuracy: 91.0%
Average Generalization Gap: 0.3%

BEST PERFORMANCE:
Lambda: 0.010
Train Accuracy: 91.3%
Test Accuracy: 91.0%

WORST PERFORMANCE:
Lambda: 0.010
Train Accuracy: 91.3%
Test Accuracy: 91.0%
